-- MySQL Script generated by MySQL Workbench
-- 03/04/16 14:04:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bus_enterprise
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bus_enterprise
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bus_enterprise` DEFAULT CHARACTER SET utf8 ;
USE `bus_enterprise` ;

-- -----------------------------------------------------
-- Table `bus_enterprise`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_enterprise`.`driver` (
  `iddriver` INT NOT NULL,
  `driver_name` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `adress` VARCHAR(45) NULL,
  PRIMARY KEY (`iddriver`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_enterprise`.`rout`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_enterprise`.`rout` (
  `idrout` INT NOT NULL,
  `hour` VARCHAR(45) NULL,
  PRIMARY KEY (`idrout`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_enterprise`.`garage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_enterprise`.`garage` (
  `idgarage` INT NOT NULL,
  `num_buses` INT NULL,
  PRIMARY KEY (`idgarage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_enterprise`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_enterprise`.`city` (
  `idcity` INT NOT NULL,
  `name_city` VARCHAR(45) NULL,
  `garage_idgarage` INT NOT NULL,
  PRIMARY KEY (`idcity`),
  INDEX `fk_city_garage_idx` (`garage_idgarage` ASC),
  CONSTRAINT `fk_city_garage`
    FOREIGN KEY (`garage_idgarage`)
    REFERENCES `bus_enterprise`.`garage` (`idgarage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_enterprise`.`model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_enterprise`.`model` (
  `num_rider` INT NULL,
  `idmodel` INT NOT NULL,
  PRIMARY KEY (`idmodel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_enterprise`.`bus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_enterprise`.`bus` (
  `idbus` INT NOT NULL,
  `garage_idgarage` INT NOT NULL,
  `driver_idconductor` INT NOT NULL,
  `rout_idrout` INT NOT NULL,
  `model_idmodel` INT NOT NULL,
  PRIMARY KEY (`idbus`),
  INDEX `fk_bus_garage1_idx` (`garage_idgarage` ASC),
  INDEX `fk_bus_driver1_idx` (`driver_idconductor` ASC),
  INDEX `fk_bus_rout1_idx` (`rout_idrout` ASC),
  INDEX `fk_bus_model1_idx` (`model_idmodel` ASC),
  CONSTRAINT `fk_bus_garage1`
    FOREIGN KEY (`garage_idgarage`)
    REFERENCES `bus_enterprise`.`garage` (`idgarage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bus_driver1`
    FOREIGN KEY (`driver_idconductor`)
    REFERENCES `bus_enterprise`.`driver` (`iddriver`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bus_rout1`
    FOREIGN KEY (`rout_idrout`)
    REFERENCES `bus_enterprise`.`rout` (`idrout`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bus_model1`
    FOREIGN KEY (`model_idmodel`)
    REFERENCES `bus_enterprise`.`model` (`idmodel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_enterprise`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_enterprise`.`schedule` (
  `idschedule` INT NOT NULL,
  `rout_idrout` INT NOT NULL,
  PRIMARY KEY (`idschedule`),
  INDEX `fk_schedule_rout1_idx` (`rout_idrout` ASC),
  CONSTRAINT `fk_schedule_rout1`
    FOREIGN KEY (`rout_idrout`)
    REFERENCES `bus_enterprise`.`rout` (`idrout`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus_enterprise`.`rout_has_city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus_enterprise`.`rout_has_city` (
  `rout_idrout` INT NOT NULL,
  `city_idcity` INT NOT NULL,
  PRIMARY KEY (`rout_idrout`, `city_idcity`),
  INDEX `fk_rout_has_city_city1_idx` (`city_idcity` ASC),
  INDEX `fk_rout_has_city_rout1_idx` (`rout_idrout` ASC),
  CONSTRAINT `fk_rout_has_city_rout1`
    FOREIGN KEY (`rout_idrout`)
    REFERENCES `bus_enterprise`.`rout` (`idrout`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rout_has_city_city1`
    FOREIGN KEY (`city_idcity`)
    REFERENCES `bus_enterprise`.`city` (`idcity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
